---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: mysql


- include: packages_apt.yml
  when: ansible_os_family == "Debian"
  tags: mysql


- include: packages_yum.yml
  when: ansible_os_family == "RedHat"
  tags: mysql


- include: mysql_configuration.yml
  tags:
     - mysql
     - mysql_config


- include: mysql_users.yml
  tags:
    - mysql
    - mysql_users


- include: mysql_databases.yml
  tags:
    - mysql
    - mysql_data

